Updated tamago version in Docker builder
This changes the errors when running `go build ./...` inside the Docker
image from:
```
/home/builder/go/pkg/mod/github.com/usbarmory/tamago@v0.0.0-20230418081853-3fd212f3d643/internal/reg/reg32.go:76:6: missing function body
note: module requires Go 1.20
/home/builder/go/pkg/mod/github.com/usbarmory/tamago@v0.0.0-20230418081853-3fd212f3d643/dma/dma.go:37:20: undefined: runtime.MemRegion
note: module requires Go 1.20
```

to:
```
/home/builder/go/pkg/mod/github.com/usbarmory/tamago@v0.0.0-20230418081853-3fd212f3d643/internal/reg/reg32.go:76:6: missing function body
/home/builder/go/pkg/mod/github.com/usbarmory/tamago@v0.0.0-20230418081853-3fd212f3d643/dma/dma.go:37:20: undefined: runtime.MemRegion
```